//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STEDENT
    {
        public int st_code { get; set; }
        public string id { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public int PersonalFilecCode { get; set; }
        public int profession { get; set; }
        public int origin { get; set; }
        public int mentally { get; set; }
        public int classCode { get; set; }
        public int codRoom { get; set; }
    
        public virtual ROOM ROOM { get; set; }
    }
}
